spring:
  config:
    import: application-local.yaml

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    oauth2:
      client:
        registration:
            google:
              client-id: ${CLIENT_ID}
              client-secret: ${CLIENT_SECRET}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${EXPIRATION}
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRATION}
server:
  servlet:
    context-path: /api/v1
  port: 8003